version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10.5
  pre_build:
    commands:
      - echo installing dependencies
      - apt-get install -y python3-venv
      - python -m venv venv
      - . venv/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - echo Build started on `date`
      - python app.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/simple_app-1.0.zip